const mongoose = require('mongoose');

const propertySchema = new mongoose.Schema({
    title: String,
    description: String,
    handover: Number,
    rentalPrice: Number,
    offeredSince: Date,
    status: String,
    availableAt: Date,
    availableUntil: Date,
    buildType: String,
    rooms: Number,
    bedrooms: Number,
    bathrooms: Number,
    price: Number,
    constructionYear: Number,
    typeOfConstruction: String,
    surfaceContent: Boolean,
    insulation: Boolean,
    heating: Boolean,
    cooling: Boolean,
    energyLabel: Boolean,
    squareMetres: Number,
    revivalLevel: Number,
    housemates: Number,
    balcony: Boolean,
    garden: Boolean,
    salvage: Boolean,
    parkingSpot: Boolean,
    garage: Boolean,
    //Extra information
    tenateAteRange: {
        min: Number,
        max: Number,
    },
    petsAllowed: Boolean,
    internetConnection: Boolean,
    // Location
    address: {
        street: String,
        city: String,
        state: String,
        country: String,
        postCode: String,
        province: String,
    },
    title: String,
    location: {
      street: String,
      city: String,
      province: String,
      // Add other location-related fields
    },
    propertyType: String,
    bedrooms: Number,
    bathrooms: Number,
    size: Number,
    furnished: Boolean,
    rentalCost: Number,
    utilitiesCost: Number,
    rentalPeriod: String,
    availabilityDate: Date,
    isAvailable: Boolean,
    description: String,
});